sudo: required
services:
  - docker

before_install:
  - docker build -t osvaldotulini/docker-react -f Dockerfile.dev .

script:
  - docker run osvaldotulini/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  backet_name: "elasticbeanstalk-eu-west-1-653023835149"
  backet_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
